spring.application.name=productjpa

#testing local Computer

#server.port=8085
#For railway
server.port=${PORT:8085}
#spring.datasource.url=jdbc:mariadb://localhost:3306/productdb2


# testing subway


#PostgreSQL Setting
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
